### PR TITLE
Added FontFamily and HeaderFontFamily properties. 

### PR DESCRIPTION
**Pull request by assemhakmeh**
Also fixed FontSize bindable property definition incorrectly referencing FontSizeProperty instead of FontSize.

### CODE REVIEW

**Comment by akgulebubekir** [comment]
I couldn't get the idea why you need to add HeaderFontFamily property? You can override HeaderLabelStyle for font family.

**Comment by assemhakmeh** [comment]
I was focused on the fixing the FontSize and adding FontFamily. Seeing how you exposed the a HeaderFontSize property, I chose to keep it consistent. However, adjusting the header using HeaderLabelStyle is a good way also. In that case, I assume you'd want to have both HeaderFontSize and HeaderFontFamily removed.

**Comment by akgulebubekir** [comment]
FontFamily feature might add(for cells instead headers and would be a good feature. Could you implement & create a pull request for that?

**Comment by assemhakmeh** [comment]
Sure. But first can you explain why HeaderFontSize should stay?

**Comment by akgulebubekir** [comment]
`HeaderTextColor` & `HeaderFontSize` planning to be obsolete. HeaderLabelStyle can do all work.

**Pull request closed without merging**
